### PR TITLE
feat: Implementations of parallel, indexing XZ compressor/decompressor

### PR DESCRIPTION
**Pull request by boulevard-h**
Pixz is a multithreaded compressor/decompressor XZ fully compatible with those provided by xz-utils and busybox. By default it adds indexing information when compressing tar files that allows fast listing and partial-archive extraction.

Log: Implementations of parallel, indexing XZ compressor/decompressor

Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/251

### CODE REVIEW

**Comment by UTsweetyfish** [comment]
nothing provides cppcheck

缺依赖

**Comment by boulevard-h** [comment]
> 

@UTsweetyfish cppcheck昨天上午已经merge：https://build.deepin.com/package/show/deepin:Develop:community/cppcheck

**Comment by boulevard-h** [comment]
@chenchongbiao

**Pull request merged**
